import { Capability } from './capability';

export type MediaType = 'video' | 'audio' | 'image' | 'carousel' | 'gif' | 'document' | 'other';

export interface MediaAuthor {
  name?: string | null;
  username?: string | null;
  avatarUrl?: string | null;
  profileUrl?: string | null;
}

/**
 * Internal model generated by platform providers.
 * May contain raw upstream tokens or debug information before normalization.
 */
export interface MediaResolution {
  mediaId: string;
  platform: string;
  mediaType: MediaType;
  title: string;
  description?: string | null;
  author?: MediaAuthor | null;
  thumbnailUrl?: string | null;
  durationSeconds?: number | null;
  sourceUrl: string;
  capabilities: Capability[];
  warnings?: string[];
  expiresAt?: string | null;
  providerMetadata?: Record<string, unknown>;
}

/**
 * Public response returned to the frontend.
 * Stripped of all provider-internal tokens, sensitive cookies, or upstream raw headers.
 */
export interface PublicMediaResponse {
  id: string;
  platform: string;
  mediaType: MediaType;
  title: string;
  description?: string | null;
  author: MediaAuthor | null;
  thumbnailUrl: string | null;
  durationSeconds: number | null;
  sourceUrl: string;
  capabilities: Capability[];
  warnings?: string[];
}
